networks:
  internal:
  alwatr-public-network:
    name: alwatr-public-network
    external: true

services:
  app:
    image: $APP_IMAGE

    cpu_count: 1
    cpu_shares: 1024
    mem_limit: 256m

    restart: unless-stopped

    networks:
      alwatr-public-network:

    environment:
      - NGINX_ACCESS_LOG=${WEBSITE_ACCESS_LOG:-off}
      - NGINX_FORCE_DOMAIN=${NGINX_FORCE_DOMAIN:-}

    logging:
      driver: json-file
      options:
        max-size: '10m'
        max-file: '2'

    labels:
      traefik.enable: true
      traefik.port: 80
      traefik.frontend.rule: Host:${DOMAIN}; PathPrefix:/;
      traefik.frontend.entryPoints: http, https
      traefik.frontend.redirect.entryPoint: https

  api:
    image: $API_IMAGE

    cpu_count: 1
    cpu_shares: 1024
    mem_limit: 256m

    restart: unless-stopped

    networks:
      internal:
      alwatr-public-network:

    depends_on:
      - storage-api

    environment:
      - STORAGE_HOST=${appId}-storage-api
      - STORAGE_PORT=80
      - STORAGE_TOKEN=${STORAGE_ACCESS_TOKEN}
      - ALWATR_DEBUG=${API_DEBUG:-}

    logging:
      driver: json-file
      options:
        max-size: '10m'
        max-file: '2'

    labels:
      traefik.enable: true
      traefik.port: 80
      traefik.frontend.rule: Host:${DOMAIN}; PathPrefix:/api/v1/;
      traefik.frontend.entryPoints: http, https
      traefik.frontend.redirect.entryPoint: https

  storage-api:
    image: ghcr.io/alwatr/storage-api:4.0.2

    cpu_count: 1
    cpu_shares: 1024
    mem_limit: 256m

    stop_grace_period: 30s

    restart: unless-stopped

    networks:
      internal:
        aliases:
          - '${appId}-storage-api'

    environment:
      - STORAGE_PATH=/data
      - ACCESS_TOKEN=${STORAGE_ACCESS_TOKEN}
      - ALWATR_DEBUG=${STORAGE_API_DEBUG:-}

    volumes:
      - type: bind
        source: ./_data/storage
        target: /data
        bind:
          create_host_path: true

    logging:
      driver: json-file
      options:
        max-size: '10m'
        max-file: '2'

  nginx-storage:
    image: ghcr.io/alwatr/nginx-storage:4.0.2

    cpu_count: 1
    cpu_shares: 1024
    mem_limit: 256m

    restart: unless-stopped

    networks:
      alwatr-public-network:

    environment:
      - NGINX_ACCESS_LOG=${NGINX_STORAGE_ACCESS_LOG:-off}

    volumes:
      - type: bind
        source: ./_data/storage
        target: /data
        bind:
          create_host_path: true

    logging:
      driver: json-file
      options:
        max-size: '10m'
        max-file: '2'

    labels:
      traefik.enable: true
      traefik.port: 80
      traefik.frontend.rule: Host:${DOMAIN}; PathPrefixStrip:/api/v0/publistore/
      traefik.frontend.entryPoints: http, https
      traefik.frontend.redirect.entryPoint: https
